name: fault_assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.2
  - matplotlib=3.5.0
  - mayavi=4.7.4
  - numpy=1.21.2
  - pytest=7.1.2
  - scikit-learn=1.0.2
  - scipy=1.9.1
  - segyio=1.9.3
  - pip:
    - opencv-python==4.6.0.66
    - patchify==0.2.3
